name: Terraform Deploy (Dev)

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: Deploy Cost Report Infra (Dev)
    runs-on: ubuntu-latest
    environment: dev   # ✅ This enables access to environment-scoped secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.TERRAFOROM_GITHUB_OIDC_ROLE_DEV }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="region=${{ env.AWS_REGION }}" -var="environment=dev"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="region=${{ env.AWS_REGION }}" -var="environment=dev"